beatsmx:
  ignore: true
  version: 0.1
  dependencies:
#    - '@BeatsBundle/Resources/public/js/jquery/jquery-1.9.1.js'
#    - '@BeatsBundle/Resources/public/js/jquery-plugins/js/jquery-migrate-1.2.1.js'
#    - 'http://code.jquery.com/jquery-1.9.1.js'
#    - 'http://code.jquery.com/jquery-migrate-1.2.1.js'
  javascripts:
    - 'mx/beats'
    - 'mx/date'
    - 'mx/model'
    - 'mx/controller'
    - 'mx/view'
    - 'mx/router'
    - 'mx/browser'
    - 'mx/flasher'
    - 'mx/blocker'
    - 'mx/reditor'
    - 'mx/field'
    - 'mx/field/widget'
    - 'mx/field/datepicker'
    - 'mx/field/number'
    - 'mx/modal/dialog'
  templates:
    - 'mx/flasher/message'
    - 'mx/field/datepicker'
    - 'mx/modal/dialog'

beats-can:
  version: 0.1
  dependencies:
    - '@BeatsBundle/Resources/public/js/ecma-extend.js'
    - '//ajax.googleapis.com/ajax/libs/jquery/1.10.2/jquery.js'
    - '//netdna.bootstrapcdn.com/bootstrap/3.0.2/js/bootstrap.js'
#    - '//netdna.bootstrapcdn.com/bootstrap/3.0.2/css/bootstrap.css'
    - '//cdnjs.cloudflare.com/ajax/libs/jstimezonedetect/1.0.4/jstz.min.js'
    - '@BeatsBundle/Resources/public/js/canjs/can-2.0.3.js'
  javascripts:
    - 'can/beats'
    - 'can/entity'
    - 'can/router'
    - 'can/control'
    - 'can/blocker'
    - 'can/flasher'
    - 'can/modal'
    - 'can/field'
    - 'can/field/widget'
    - 'can/field/datepicker'
    - 'can/field/number'
    - 'can/modal/dialog'
  templates:
    - 'can/flasher/message'
    - 'can/field/datepicker'
    - 'can/modal/dialog'

ecma-jquery-boostrap:
  version: 0.1
  dependencies:
  - '@BeatsBundle/Resources/public/js/ecma-extend.js'
  - '//ajax.googleapis.com/ajax/libs/jquery/1.10.2/jquery.js'
  - '//cdnjs.cloudflare.com/ajax/libs/jstimezonedetect/1.0.4/jstz.min.js'
  - '//netdna.bootstrapcdn.com/bootstrap/3.0.2/js/bootstrap.js'
#  - '//netdna.bootstrapcdn.com/bootstrap/3.0.2/css/bootstrap.css'
