beats-can:
  version: 0.1
  dependencies:
    - '@BeatsBundle/Resources/public/js/ecma-extend.js'
    - '//ajax.googleapis.com/ajax/libs/jquery/1.10.2/jquery.js'
    - '@BeatsBundle/Resources/public/js/jquery-extend.js'
    - '//netdna.bootstrapcdn.com/bootstrap/3.0.2/js/bootstrap.js'
    - '@BeatsBundle/Resources/public/js/bootstrap-extend.js'
#    - '//netdna.bootstrapcdn.com/bootstrap/3.0.2/css/bootstrap.css'
    - '//cdnjs.cloudflare.com/ajax/libs/jstimezonedetect/1.0.4/jstz.min.js'
    - '@BeatsBundle/Resources/public/js/canjs/can-2.0.3.js'
  javascripts:
    - 'can/beats'
    - 'can/entity'
    - 'can/router'
    - 'can/translator'
    - 'can/control'
    - 'can/blocker'
    - 'can/flasher'
    - 'can/modal'
    - 'can/modal/dialog'
  stylesheets:
    - 'can/blocker'
  templates:
    - 'can/flasher/message'
    - 'can/modal/dialog'

#beats-can-modal:
#  version: 0.1
#  javascripts:
#    - 'can/modal/dialog'
#  templates:
#    - 'can/modal/dialog'

beats-can-form:
  version: 0.1
  javascripts:
    - 'can/field'
    - 'can/field/reditor'
    - 'can/field/widget'
    - 'can/field/datetime'
    - 'can/field/number'
  templates:
    - 'can/field/datetime'
ecma-jquery-boostrap:
  version: 0.1
  dependencies:
  - '@BeatsBundle/Resources/public/js/ecma-extend.js'
  - '//ajax.googleapis.com/ajax/libs/jquery/1.10.2/jquery.js'
  - '//cdnjs.cloudflare.com/ajax/libs/jstimezonedetect/1.0.4/jstz.min.js'
  - '//netdna.bootstrapcdn.com/bootstrap/3.0.2/js/bootstrap.js'
#  - '//netdna.bootstrapcdn.com/bootstrap/3.0.2/css/bootstrap.css'
