beats-can:
  version: 0.1
  dependencies:
    - '@BeatsBundle/Resources/public/js/ecma-extend.js'
    - '//code.jquery.com/jquery-1.11.2.js'
    - '@BeatsBundle/Resources/public/js/jquery-extend.js'
    - '//maxcdn.bootstrapcdn.com/bootstrap/3.3.4/js/bootstrap.js'
    - '@BeatsBundle/Resources/public/js/bootstrap-extend.js'
    - '//cdnjs.cloudflare.com/ajax/libs/hammer.js/2.0.4/hammer.js'
    - '@BeatsBundle/Resources/public/js/jquery.hammer.js'
    - '//cdnjs.cloudflare.com/ajax/libs/jstimezonedetect/1.0.4/jstz.min.js'
    - '@BeatsBundle/Resources/public/js/canjs/can-2.0.3.js'
#    - '//maxcdn.bootstrapcdn.com/bootstrap/3.3.4/css/bootstrap.css'
  javascripts:
    - 'can/beats'
    - 'can/entity'
    - 'can/router'
    - 'can/translator'
    - 'can/control'
    - 'can/blocker'
    - 'can/flasher'
    - 'can/modal'
    - 'can/modal/dialog'
  stylesheets:
    - 'can/blocker'
  templates:
    - 'can/flasher/message'
    - 'can/modal/dialog'

#beats-can-modal:
#  version: 0.1
#  javascripts:
#    - 'can/modal/dialog'
#  templates:
#    - 'can/modal/dialog'

beats-can-form:
  version: 0.1
  dependencies:
    - '@BeatsBundle/Resources/lib/js/jquery-plugins/twitter/typeahead.js-0.11.1/dist/bloodhound.js'
  javascripts:
    - 'can/field'
    - 'can/field/reditor'
    - 'can/field/widget'
    - 'can/field/datetime'
    - 'can/field/number'
    - 'can/field/image'
    - 'can/field/autocomplete'
    - 'can/suggestioner'
  stylesheets:
    - 'can/field/image'
    - 'can/field/autocomplete'
  templates:
    - 'can/field/datetime'
    - 'can/field/autocomplete'
ecma-jquery-boostrap:
  version: 0.1
  dependencies:
  - '@BeatsBundle/Resources/public/js/ecma-extend.js'
  - '//code.jquery.com/jquery-1.11.2.js'
  - '//cdnjs.cloudflare.com/ajax/libs/jstimezonedetect/1.0.4/jstz.min.js'
  - '//maxcdn.bootstrapcdn.com/bootstrap/3.3.4/js/bootstrap.js'
#  - '//maxcdn.bootstrapcdn.com/bootstrap/3.3.4/css/bootstrap.css'
