beatsmx:
  ignore: true
  version: 0.1
  dependencies:
#    - '@BeatsBundle/Resources/public/js/jquery/jquery-1.9.1.js'
#    - '@BeatsBundle/Resources/public/js/jquery-plugins/js/jquery-migrate-1.2.1.js'
#    - 'http://code.jquery.com/jquery-1.9.1.js'
#    - 'http://code.jquery.com/jquery-migrate-1.2.1.js'
  javascripts:
    - 'beats'
    - 'date'
    - 'model'
    - 'controller'
    - 'view'
    - 'router'
    - 'browser'
    - 'flasher'
    - 'blocker'
    - 'reditor'
    - 'field'
    - 'field/widget'
    - 'field/datepicker'
    - 'field/number'
    - 'modal/dialog'
  templates:
    - 'flasher/message'
    - 'field/datepicker'
    - 'modal/dialog'

beats-can:
  version: 0.1
  dependencies:
#    - 'http://ajax.googleapis.com/ajax/libs/jquery/1.10.2/jquery.js'
#    - '//cdnjs.cloudflare.com/ajax/libs/jstimezonedetect/1.0.4/jstz.min.js'
#    - '@BeatsBundle/Resources/public/js/canjs/can-2.0.3.js'
  javascripts:
    - 'can/beats'
    - 'can/router'
    - 'can/control'
    - 'can/blocker'
    - 'can/flasher'
    - 'can/modal'
    - 'can/field'
    - 'can/field/widget'
    - 'can/field/datepicker'
    - 'can/field/number'
    - 'can/modal/dialog'
  templates:
    - 'can/flasher/message'
    - 'can/field/datepicker'
    - 'can/modal/dialog'
